// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/dns.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  RustLib._();
  @internal
  static final RustLib instance = RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 213078427;

  static const ExternalLibraryLoaderConfig kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'jetlag_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  DnsProvider crateApiDnsCreateCustomProvider({
    required String id,
    required String name,
    required String primaryDns,
    required String secondaryDns,
    String? dohUrl,
    String? dotHostname,
  });

  List<NetworkInterface> crateApiDnsGetActiveInterfaces();

  List<DnsProvider> crateApiDnsGetBuiltinProviders();

  List<String> crateApiDnsGetCurrentDns({String? interfaceName});

  DnsProvider? crateApiDnsGetProvider({required String id});

  Future<void> crateApiSimpleInitApp();

  Future<DnsChangeResult> crateApiDnsResetDns({String? interfaceName});

  Future<DnsChangeResult> crateApiDnsSetDns({
    required DnsProvider provider,
    String? interfaceName,
  });

  bool crateApiDnsValidateAddress({required String addr});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  DnsProvider crateApiDnsCreateCustomProvider({
    required String id,
    required String name,
    required String primaryDns,
    required String secondaryDns,
    String? dohUrl,
    String? dotHostname,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(primaryDns, serializer);
          sse_encode_String(secondaryDns, serializer);
          sse_encode_opt_String(dohUrl, serializer);
          sse_encode_opt_String(dotHostname, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dns_provider,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDnsCreateCustomProviderConstMeta,
        argValues: <dynamic>[
          id,
          name,
          primaryDns,
          secondaryDns,
          dohUrl,
          dotHostname,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsCreateCustomProviderConstMeta =>
      const TaskConstMeta(
        debugName: 'create_custom_provider',
        argNames: <String>[
          'id',
          'name',
          'primaryDns',
          'secondaryDns',
          'dohUrl',
          'dotHostname',
        ],
      );

  @override
  List<NetworkInterface> crateApiDnsGetActiveInterfaces() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_network_interface,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsGetActiveInterfacesConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsGetActiveInterfacesConstMeta =>
      const TaskConstMeta(
        debugName: 'get_active_interfaces',
        argNames: <String>[],
      );

  @override
  List<DnsProvider> crateApiDnsGetBuiltinProviders() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_dns_provider,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsGetBuiltinProvidersConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsGetBuiltinProvidersConstMeta =>
      const TaskConstMeta(
        debugName: 'get_builtin_providers',
        argNames: <String>[],
      );

  @override
  List<String> crateApiDnsGetCurrentDns({String? interfaceName}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_opt_String(interfaceName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsGetCurrentDnsConstMeta,
        argValues: <dynamic>[interfaceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsGetCurrentDnsConstMeta => const TaskConstMeta(
    debugName: 'get_current_dns',
    argNames: <String>['interfaceName'],
  );

  @override
  DnsProvider? crateApiDnsGetProvider({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_dns_provider,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsGetProviderConstMeta,
        argValues: <dynamic>[id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsGetProviderConstMeta =>
      const TaskConstMeta(debugName: 'get_provider', argNames: <String>['id']);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (NativePortType port_) {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: <dynamic>[],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: 'init_app', argNames: <String>[]);

  @override
  Future<DnsChangeResult> crateApiDnsResetDns({String? interfaceName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (NativePortType port_) {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_opt_String(interfaceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dns_change_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsResetDnsConstMeta,
        argValues: <dynamic>[interfaceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsResetDnsConstMeta => const TaskConstMeta(
    debugName: 'reset_dns',
    argNames: <String>['interfaceName'],
  );

  @override
  Future<DnsChangeResult> crateApiDnsSetDns({
    required DnsProvider provider,
    String? interfaceName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (NativePortType port_) {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_box_autoadd_dns_provider(provider, serializer);
          sse_encode_opt_String(interfaceName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dns_change_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsSetDnsConstMeta,
        argValues: <dynamic>[provider, interfaceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsSetDnsConstMeta => const TaskConstMeta(
    debugName: 'set_dns',
    argNames: <String>['provider', 'interfaceName'],
  );

  @override
  bool crateApiDnsValidateAddress({required String addr}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final SseSerializer serializer = SseSerializer(
            generalizedFrbRustBinding,
          );
          sse_encode_String(addr, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDnsValidateAddressConstMeta,
        argValues: <dynamic>[addr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDnsValidateAddressConstMeta => const TaskConstMeta(
    debugName: 'validate_address',
    argNames: <String>['addr'],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DnsProvider dco_decode_box_autoadd_dns_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dns_provider(raw);
  }

  @protected
  DnsChangeMethod dco_decode_dns_change_method(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DnsChangeMethod.values[raw as int];
  }

  @protected
  DnsChangeResult dco_decode_dns_change_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final List<dynamic> arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DnsChangeResult(
      success: dco_decode_bool(arr[0]),
      method: dco_decode_dns_change_method(arr[1]),
      message: dco_decode_String(arr[2]),
      requiresUserAction: dco_decode_bool(arr[3]),
      userActionMessage: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DnsProvider dco_decode_dns_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final List<dynamic> arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return DnsProvider(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      primaryDns: dco_decode_String(arr[2]),
      secondaryDns: dco_decode_String(arr[3]),
      primaryDnsIpv6: dco_decode_opt_String(arr[4]),
      secondaryDnsIpv6: dco_decode_opt_String(arr[5]),
      dohUrl: dco_decode_opt_String(arr[6]),
      dotHostname: dco_decode_opt_String(arr[7]),
      description: dco_decode_String(arr[8]),
      isCustom: dco_decode_bool(arr[9]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DnsProvider> dco_decode_list_dns_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dns_provider).toList();
  }

  @protected
  List<NetworkInterface> dco_decode_list_network_interface(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_network_interface).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NetworkInterface dco_decode_network_interface(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final List<dynamic> arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NetworkInterface(
      name: dco_decode_String(arr[0]),
      index: dco_decode_u_32(arr[1]),
      isActive: dco_decode_bool(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DnsProvider? dco_decode_opt_box_autoadd_dns_provider(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dns_provider(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final Uint8List inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DnsProvider sse_decode_box_autoadd_dns_provider(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return sse_decode_dns_provider(deserializer);
  }

  @protected
  DnsChangeMethod sse_decode_dns_change_method(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int inner = sse_decode_i_32(deserializer);
    return DnsChangeMethod.values[inner];
  }

  @protected
  DnsChangeResult sse_decode_dns_change_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final bool var_success = sse_decode_bool(deserializer);
    final DnsChangeMethod var_method = sse_decode_dns_change_method(
      deserializer,
    );
    final String var_message = sse_decode_String(deserializer);
    final bool var_requiresUserAction = sse_decode_bool(deserializer);
    final String? var_userActionMessage = sse_decode_opt_String(deserializer);
    return DnsChangeResult(
      success: var_success,
      method: var_method,
      message: var_message,
      requiresUserAction: var_requiresUserAction,
      userActionMessage: var_userActionMessage,
    );
  }

  @protected
  DnsProvider sse_decode_dns_provider(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final String var_id = sse_decode_String(deserializer);
    final String var_name = sse_decode_String(deserializer);
    final String var_primaryDns = sse_decode_String(deserializer);
    final String var_secondaryDns = sse_decode_String(deserializer);
    final String? var_primaryDnsIpv6 = sse_decode_opt_String(deserializer);
    final String? var_secondaryDnsIpv6 = sse_decode_opt_String(deserializer);
    final String? var_dohUrl = sse_decode_opt_String(deserializer);
    final String? var_dotHostname = sse_decode_opt_String(deserializer);
    final String var_description = sse_decode_String(deserializer);
    final bool var_isCustom = sse_decode_bool(deserializer);
    return DnsProvider(
      id: var_id,
      name: var_name,
      primaryDns: var_primaryDns,
      secondaryDns: var_secondaryDns,
      primaryDnsIpv6: var_primaryDnsIpv6,
      secondaryDnsIpv6: var_secondaryDnsIpv6,
      dohUrl: var_dohUrl,
      dotHostname: var_dotHostname,
      description: var_description,
      isCustom: var_isCustom,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<String> ans_ = <String>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DnsProvider> sse_decode_list_dns_provider(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<DnsProvider> ans_ = <DnsProvider>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dns_provider(deserializer));
    }
    return ans_;
  }

  @protected
  List<NetworkInterface> sse_decode_list_network_interface(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    final int len_ = sse_decode_i_32(deserializer);
    final List<NetworkInterface> ans_ = <NetworkInterface>[];
    for (int idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_network_interface(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final int len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NetworkInterface sse_decode_network_interface(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final String var_name = sse_decode_String(deserializer);
    final int var_index = sse_decode_u_32(deserializer);
    final bool var_isActive = sse_decode_bool(deserializer);
    return NetworkInterface(
      name: var_name,
      index: var_index,
      isActive: var_isActive,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_String(deserializer);
    } else {
      return null;
    }
  }

  @protected
  DnsProvider? sse_decode_opt_box_autoadd_dns_provider(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return sse_decode_box_autoadd_dns_provider(deserializer);
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dns_provider(
    DnsProvider self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dns_provider(self, serializer);
  }

  @protected
  void sse_encode_dns_change_method(
    DnsChangeMethod self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dns_change_result(
    DnsChangeResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_dns_change_method(self.method, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_bool(self.requiresUserAction, serializer);
    sse_encode_opt_String(self.userActionMessage, serializer);
  }

  @protected
  void sse_encode_dns_provider(DnsProvider self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.primaryDns, serializer);
    sse_encode_String(self.secondaryDns, serializer);
    sse_encode_opt_String(self.primaryDnsIpv6, serializer);
    sse_encode_opt_String(self.secondaryDnsIpv6, serializer);
    sse_encode_opt_String(self.dohUrl, serializer);
    sse_encode_opt_String(self.dotHostname, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_bool(self.isCustom, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final String item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dns_provider(
    List<DnsProvider> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final DnsProvider item in self) {
      sse_encode_dns_provider(item, serializer);
    }
  }

  @protected
  void sse_encode_list_network_interface(
    List<NetworkInterface> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final NetworkInterface item in self) {
      sse_encode_network_interface(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_network_interface(
    NetworkInterface self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.index, serializer);
    sse_encode_bool(self.isActive, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dns_provider(
    DnsProvider? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dns_provider(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
