// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'api/dns.dart';
import 'frb_generated.dart';
import 'models.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DnsProvider dco_decode_box_autoadd_dns_provider(dynamic raw);

  @protected
  DnsChangeMethod dco_decode_dns_change_method(dynamic raw);

  @protected
  DnsChangeResult dco_decode_dns_change_result(dynamic raw);

  @protected
  DnsProvider dco_decode_dns_provider(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DnsProvider> dco_decode_list_dns_provider(dynamic raw);

  @protected
  List<NetworkInterface> dco_decode_list_network_interface(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NetworkInterface dco_decode_network_interface(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DnsProvider? dco_decode_opt_box_autoadd_dns_provider(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DnsProvider sse_decode_box_autoadd_dns_provider(SseDeserializer deserializer);

  @protected
  DnsChangeMethod sse_decode_dns_change_method(SseDeserializer deserializer);

  @protected
  DnsChangeResult sse_decode_dns_change_result(SseDeserializer deserializer);

  @protected
  DnsProvider sse_decode_dns_provider(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DnsProvider> sse_decode_list_dns_provider(SseDeserializer deserializer);

  @protected
  List<NetworkInterface> sse_decode_list_network_interface(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NetworkInterface sse_decode_network_interface(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DnsProvider? sse_decode_opt_box_autoadd_dns_provider(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dns_provider(
    DnsProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_change_method(
    DnsChangeMethod self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_change_result(
    DnsChangeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dns_provider(DnsProvider self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dns_provider(
    List<DnsProvider> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network_interface(
    List<NetworkInterface> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_interface(
    NetworkInterface self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dns_provider(
    DnsProvider? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary();
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
