// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter/foundation.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

/// Platform-specific method used to change DNS.
enum DnsChangeMethod {
  /// Android: Open Private DNS settings for user to configure
  privateDnsSettings,

  /// Android: Direct change via root access (settings put global)
  rootAccess,

  /// iOS: NEDNSSettingsManager programmatic profile
  networkExtension,

  /// iOS fallback: Open Settings app for manual DNS activation
  settingsRedirect,

  /// Windows: SetInterfaceDnsSettings via elevated service
  windowsApi,

  /// Linux: D-Bus call to systemd-resolved
  resolvectl,

  /// macOS: networksetup CLI command
  networksetup,
}
/// Result of a DNS change operation.
@immutable
class DnsChangeResult {
  const DnsChangeResult({
    required this.success,
    required this.method,
    required this.message,
    required this.requiresUserAction,
    this.userActionMessage,
  });

  /// Whether the operation succeeded
  final bool success;

  /// The method that was used
  final DnsChangeMethod method;

  /// Human-readable message
  final String message;

  /// If the user needs to manually complete a step (e.g., iOS Settings activation)
  final bool requiresUserAction;

  /// Instructions for the user if manual action is needed
  final String? userActionMessage;

  @override
  int get hashCode =>
      success.hashCode ^
      method.hashCode ^
      message.hashCode ^
      requiresUserAction.hashCode ^
      userActionMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DnsChangeResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          method == other.method &&
          message == other.message &&
          requiresUserAction == other.requiresUserAction &&
          userActionMessage == other.userActionMessage;
}
/// Represents a DNS provider with all its configuration details.
@immutable
class DnsProvider {
  const DnsProvider({
    required this.id,
    required this.name,
    required this.primaryDns,
    required this.secondaryDns,
    this.primaryDnsIpv6,
    this.secondaryDnsIpv6,
    this.dohUrl,
    this.dotHostname,
    required this.description,
    required this.isCustom,
  });

  /// Unique identifier for the provider (e.g., "cloudflare", "google", "custom_1")
  final String id;

  /// Human-readable name (e.g., "Cloudflare")
  final String name;

  /// Primary DNS server IPv4 address
  final String primaryDns;

  /// Secondary DNS server IPv4 address
  final String secondaryDns;

  /// Optional primary IPv6 DNS address
  final String? primaryDnsIpv6;

  /// Optional secondary IPv6 DNS address
  final String? secondaryDnsIpv6;

  /// DNS-over-HTTPS URL (e.g., "<https://cloudflare-dns.com/dns-query>")
  final String? dohUrl;

  /// DNS-over-TLS hostname (e.g., "cloudflare-dns.com")
  final String? dotHostname;

  /// Short description of the provider
  final String description;

  /// Whether this is a user-defined custom provider
  final bool isCustom;

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      primaryDns.hashCode ^
      secondaryDns.hashCode ^
      primaryDnsIpv6.hashCode ^
      secondaryDnsIpv6.hashCode ^
      dohUrl.hashCode ^
      dotHostname.hashCode ^
      description.hashCode ^
      isCustom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DnsProvider &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          primaryDns == other.primaryDns &&
          secondaryDns == other.secondaryDns &&
          primaryDnsIpv6 == other.primaryDnsIpv6 &&
          secondaryDnsIpv6 == other.secondaryDnsIpv6 &&
          dohUrl == other.dohUrl &&
          dotHostname == other.dotHostname &&
          description == other.description &&
          isCustom == other.isCustom;
}

/// Represents a network interface on the system.
@immutable
class NetworkInterface {
  const NetworkInterface({
    required this.name,
    required this.index,
    required this.isActive,
  });

  /// Interface name (e.g., "Wi-Fi", "eth0", "Ethernet")
  final String name;

  /// Interface index (used by Linux D-Bus API)
  final int index;

  /// Whether this interface is currently active/up
  final bool isActive;

  @override
  int get hashCode => name.hashCode ^ index.hashCode ^ isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInterface &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          index == other.index &&
          isActive == other.isActive;
}
