// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../models.dart';

/// Get all built-in DNS providers.
List<DnsProvider> getBuiltinProviders() =>
    RustLib.instance.api.crateApiDnsGetBuiltinProviders();

/// Get a single provider by ID.
DnsProvider? getProvider({required String id}) =>
    RustLib.instance.api.crateApiDnsGetProvider(id: id);

/// Create a custom DNS provider. Returns an error string if validation fails.
DnsProvider createCustomProvider({
  required String id,
  required String name,
  required String primaryDns,
  required String secondaryDns,
  String? dohUrl,
  String? dotHostname,
}) => RustLib.instance.api.crateApiDnsCreateCustomProvider(
  id: id,
  name: name,
  primaryDns: primaryDns,
  secondaryDns: secondaryDns,
  dohUrl: dohUrl,
  dotHostname: dotHostname,
);

/// Validate a DNS address (IPv4 or IPv6).
bool validateAddress({required String addr}) =>
    RustLib.instance.api.crateApiDnsValidateAddress(addr: addr);

/// Set DNS on the current platform (desktop: Windows/Linux/macOS).
/// On mobile platforms, this returns a failure — use MethodChannel instead.
Future<DnsChangeResult> setDns({
  required DnsProvider provider,
  String? interfaceName,
}) => RustLib.instance.api.crateApiDnsSetDns(
  provider: provider,
  interfaceName: interfaceName,
);

/// Reset DNS to system defaults on the current platform (desktop only).
Future<DnsChangeResult> resetDns({String? interfaceName}) =>
    RustLib.instance.api.crateApiDnsResetDns(interfaceName: interfaceName);

/// Get the current system DNS servers (desktop only).
List<String> getCurrentDns({String? interfaceName}) =>
    RustLib.instance.api.crateApiDnsGetCurrentDns(interfaceName: interfaceName);

/// List active network interfaces (desktop only).
List<NetworkInterface> getActiveInterfaces() =>
    RustLib.instance.api.crateApiDnsGetActiveInterfaces();
